name: RCC
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.1
  - numpy>=1.18.0
  - pandas>=1.0.0
  - scikit-learn>=0.22.0
  - matplotlib>=3.1.0
  - seaborn>=0.10.0
  - pip
  - pip:
      - pytest>=5.3.5
      - jupyterlab>=2.0.0
      - flake8
      - black